MonitoringStation_Storage_Text_BlueDoorGone::
	.string "The BLUE KEY unlocked the door!$"

MonitoringStation_Storage_Text_BlueDoor::
	.string "This door is electronically locked.\n"
	.string "A specific keycard can unlock it.$"
	
MonitoringStation_Storage_Text_Agh::
	.string "AAGH!!$"

MonitoringStation_Storage_Text_Explain::
	.string "Huh, what?!\n"
	.string "Stop startling me!\p"
	.string "Wait, you're just a kid!\n"
	.string "You're not supposed to be here!\p"
	.string "I guess the elevator malfunctioned\n"
	.string "and brought you here, am I right?$"
	
MonitoringStation_Storage_Text_RedKeyAdmin::
	.string "Look, I know we're the bad guys,\n"
	.string "but maybe you can help us.\p"
	.string "The only way to get out of here is\n"
	.string "by climbing the staircase standing\p"
	.string "next to the elevator.\p"
	.string "However, to access the staircase,\n"
	.string "you will need a RED KEY.\p"
	.string "Only two people in this base have\n"
	.string "been given such a key by our BOSS.\p"
	.string "One of them is the base's ADMIN, who\n"
	.string "oversees the monitoring office here.\p"
	.string "Then there is the UNDERBOSS, who\n"
	.string "has command over this entire base.\p"
	.string "Our UNDERBOSS, the coward, is likely\n"
	.string "hiding away inside his own office\p"
	.string "located downstairs.\p"
	.string "However, I saw the ADMIN at work at\n"
	.string "the monitoring office, which you\p"
	.string "came through on your way here.\p"
	.string "It's likely that the emergency doors\n"
	.string "have her locked up inside her room.\p"
	.string "That means you will have to restore\n"
	.string "the power by reactivating the\p"
	.string "machine located at the end of the\n"
	.string "mechanical room.\p"
	.string "Honestly, you don't have much choice\n"
	.string "other than to help us.\p"
	.string "After all, you're stuck here, too!\p"
	.string "Now, get a move on!\p"
	.string "Restore the power and get that\n"
	.string "RED KEY!$"
	
MonitoringStation_Storage_Text_Done::
	.string "Huh, what?!\n"
	.string "Stop startling me!\p"
	.string "What are you waiting for?!\p"
	.string "Restore the power and get that\n"
	.string "RED KEY!$"
	
MonitoringStation_Storage_Text_Phew::
	.string "Ah, it's you!\n"
	.string "Seems you have restored the power.\p"
	.string "Good job, little guy.\p"
	.string "Now, go and find the ADMIN and\n"
	.string "ask for that RED KEY!$"

MonitoringStation_Storage_Text_BlueKey::
	.string "You got the RED KEY?\p"
	.string "…\p"
	.string "Oh.\p"
	.string "In that case, you will need a\n"
	.string "YELLOW KEY to get into the\p"
	.string "office of the UNDERBOSS.\p"
	.string "I don't have one here, though.\n"
	.string "You will have to ask someone else.$"