MonitoringStation_Shortcut_Text_AdminDefense1::
	.string "Get away from me, you beast!$"
	
MonitoringStation_Shortcut_Text_AdminDefense2::
	.string "AAAAH!!$"
	
MonitoringStation_Shortcut_Text_AdminDefense3::
	.string "P-please…\n"
	.string "Just leave me alone now…$"
	
MonitoringStation_Shortcut_Text_Scared::
	.string "Because of the monster's ambush,\n"
	.string "{PLAYER}'s POKéMON are now too\p"
	.string "scared to come out of their\n"
	.string "POKé BALLS.\p"
	.string "HMs cannot be used for the\n"
	.string "time being.$"