PokeCenter_Text_NoHope::
	.string "THERE IS NO HOPE OF ESCAPE.$"
	
PokeCenter_Text_Pointless::
	.string "IT IS POINTLESS TO TRY.$"
	
PokeCenter_Text_BeyondReach::
	.string "THE END IS BEYOND REACH.$"
	
PokeCenter_Text_DontGiveUp::
	.string "YOU WILL NOT GIVE UP, WILL YOU?$"
	
PokeCenter_Text_KeepTrying::
	.string "WHY DO YOU KEEP TRYING?$"
	
PokeCenter_Text_Determination::
	.string "I ADMIRE YOUR DETERMINATION…$"
	
PokeCenter_Text_AlmostThere::
	.string "YOUR MIND IS STRONG…$"
	
PokeCenter_Text_TheEnd::
	.string "WITH YOUR COURAGE AND PERSEVERANCE\n"
	.string "YOU OVERCAME MY ILLUSION.\p"
	.string "I WILL HAVE TO TRY…\n"
	.string "SOMETHING ELSE…$"
	
PokeCenter_Text_Closed::
	.string "The way to safety has been closed…$"
	
PokeCenter_Text_Adventure::
	.string "PATH OF ADVENTURE$"