MonitoringStation_Central_Text_QuartetRock::
	.string "… A boulder is blocking the way to\n"
	.string "the entrance hallway.\p"
	.string "Someone has used a POKéMON to push\n"
	.string "it in front of the doorway.\p"
	.string "We will need a strong POKéMON to\n"
	.string "take care of it.\p"
	.string "Since your POKéMON are too afraid\n"
	.string "to function properly… Hmm…\p"
	.string "I recall there being a KANGASKHAN\n"
	.string "in the holding room.\p"
	.string "That one would be perfect for\n"
	.string "our little plan.\p"
	.string "If you go free that caged POKéMON,\n"
	.string "I can command it to use STRENGTH\p"
	.string "against that boulder.$"
	
MonitoringStation_Central_Text_KangaHappy::
	.string "KANGASKHAN is happy to see you!$"
	
MonitoringStation_Central_Text_QuartetKanga::
	.string "Did you manage to free the POKéMON\n"
	.string "I asked for?$"
	
MonitoringStation_Central_Text_QuartetKangaNo::
	.string "You haven't even looked for it?\n"
	.string "Stop wasting time!\p"
	.string "We need that KANGASKHAN!$"
	
MonitoringStation_Central_Text_QuartetKangaYes::
	.string "You've been to the holding room?\n"
	.string "And you didn't find KANGASKHAN?\p"
	.string "Ugh, I'll just go free it myself.\n"
	.string "Wait here.$"

MonitoringStation_Central_Text_Quartet::
	.string "Watch this KANGASKHAN do its work.$"
	
MonitoringStation_Central_Text_Quartet2::
	.string "KANGASKHAN! Use STRENGTH!!$"
	
MonitoringStation_Central_Text_Kanga::
	.string "KANGASKHAN: Kan-Ga!!$"
	
MonitoringStation_Central_Text_Quartet3::
	.string "Okay, let's go.$"

MonitoringStation_Central_Text_GreyDoor::
	.string "The power outage has activated the\n"
	.string "emergency doors.$"

MonitoringStation_Central_Text_RocketAttack::
	.string "MACHOKE!\n"
	.string "Use VITAL THROW!!$"
	
MonitoringStation_Central_Text_MachokeNoise::
	.string "MACHOKE: Gwoooh!$"
	
MonitoringStation_Central_Text_RocketWhat::
	.string "W-what??!$"
	
MonitoringStation_Central_Text_RocketNo::
	.string "N-no! Wait, NO!!$"
	
MonitoringStation_Central_Text_RocketOh::
	.string "Huh? It went… r-right through me?$"
	
MonitoringStation_Central_Text_RocketAh::
	.string "Waaaaaaaaaaaaaaaaaaahh!!!$"

MonitoringStation_Central_Text_Admin::
	.string "A… child?\n"
	.string "This day can't get any stranger.\p"
	.string "You want my RED KEY, right?\p"
	.string "Well, unfortunately, I no longer\n"
	.string "have it.\p"
	.string "It was taken from me by the ghost\n"
	.string "you have probably seen wandering\p"
	.string "around.\p"
	.string "Our UNDERBOSS has the other key,\n"
	.string "so you should go look for him.\p"
	.string "The alternative would be to\n"
	.string "challenge that monster…\p"
	.string "I suggest you search for a way to\n"
	.string "get into the UNDERBOSS' office.$"

MonitoringStation_Central_Text_Admin2::
	.string "Well, what are you waiting for?$"
	
MonitoringStation_Central_Text_Boulder::
	.string "It's the boulder that was thrown\n"
	.string "by the mysterious shadow…$"
	
MonitoringStation_Central_Text_Boulder2::
	.string "It's the boulder that was thrown\n"
	.string "by the mysterious shadow…\p"
	.string "Your POKéMON are too afraid to\n"
	.string "show themselves.\p"
	.string "STRENGTH cannot be used.$"