Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Let's see…\n"
	.string "Uh-oh! You don't have the required\l"
	.string "GYM BADGE to get this item!$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Oh. I see.\p"
	.string "When you get the right GYM BADGE,\n"
	.string "come back for the {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh! I see you don't have any\n"
	.string "room for the {STR_VAR_2}.$"
