Braille_Text_Up::
	.braille "UP$"

Braille_Text_Down::
	.braille "DOWN$"

Braille_Text_Right::
	.braille "RIGHT$"

Braille_Text_Left::
	.braille "LEFT$"

Braille_Text_Cut::
	.braille "CUT$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille ".$"

Braille_Text_Comma::
	.braille ",$"

Braille_Text_Everything::
	.braille "EVERYTHING$"

Braille_Text_HasMeaning1::
	.braille "HAS MEANING$"

Braille_Text_Existence::
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2::
	.braille "HAS MEANING$"

Braille_Text_BeingAlive::
	.braille "BEING ALIVE$"

Braille_Text_HasMeaning3::
	.braille "HAS MEANING$"

Braille_Text_HaveDreams::
	.braille "HAVE DREAMS$"

Braille_Text_UsePower::
	.braille "USE POWER.$"

Braille_Text_LetTheTwo::
	.braille "LET THE TWO$"

Braille_Text_Glittering::
	.braille "GLITTERING$"

Braille_Text_Stones::
	.braille "STONES$"

Braille_Text_OneInRed::
	.braille "ONE IN RED$"

Braille_Text_OneInBlue::
	.braille "ONE IN BLUE$"

Braille_Text_ConnectThe::
	.braille "CONNECT THE$"

Braille_Text_Past::
	.braille "PAST.$"

Braille_Text_TwoFriends::
	.braille "TWO FRIENDS$"

Braille_Text_Sharing::
	.braille "SHARING$"

Braille_Text_PowerOpen::
	.braille "POWER OPEN$"

Braille_Text_AWindowTo::
	.braille "A WINDOW TO$"

Braille_Text_ANewWorld::
	.braille "A NEW WORLD$"

Braille_Text_ThatGlows::
	.braille "THAT GLOWS.$"

Braille_Text_TheNext::
	.braille "THE NEXT$"

Braille_Text_WorldWaits::
	.braille "WORLD WAITS$"

Braille_Text_ForYou::
	.braille "FOR YOU.$"
		
Braille_Text_Submit::
	.braille "SUBMIT.$"
	
Braille_Text_Welcome::
	.braille "WELCOME.$"
	
Braille_Text_Journey::
	.braille "THIS JOURNEY$"
	
Braille_Text_Gone::
	.braille "HAS GONE$"
	
Braille_Text_For::
	.braille "ON FOR$"
	
Braille_Text_Enough::
	.braille "LONG ENOUGH.$"
	
Braille_Text_Give::
	.braille "TO GIVE$"
	
Braille_Text_Life::
	.braille "LIFE TO$"
	
Braille_Text_Idea::
	.braille "AN IDEA IS$"
	
Braille_Text_Achieve::
	.braille "TO ACHIEVE$"
	
Braille_Text_Highest::
	.braille "THE HIGHEST$"
	
Braille_Text_Purpose::
	.braille "PURPOSE.$"
	
Braille_Text_Memories::
	.braille "MEMORIES OF$"
	
Braille_Text_Past2::
	.braille "PAST$"
	
Braille_Text_Rekindled::
	.braille "REKINDLED$"
	
Braille_Text_Buried::
	.braille "BURIED$"
	
Braille_Text_Concepts::
	.braille "CONCEPTS$"
	
Braille_Text_Reused::
	.braille "REUSED.$"
	
Braille_Text_Community::
	.braille "BY COMMUNITY$"
	
Braille_Text_Reunited::
	.braille "REUNITED.$"
	
Braille_Text_Given::
	.braille "AND GIVEN$"
	
Braille_Text_Shape::
	.braille "SHAPE$"
	
Braille_Text_Passion::
	.braille "BY PASSION.$"
	
Braille_Text_Continue::
	.braille "CONTINUE$"
	
Braille_Text_Legacy::
	.braille "THE LEGACY.$"
	
Braille_Text_Create::
	.braille "CREATE$"
	
Braille_Text_Worlds::
	.braille "NEW WORLDS$"
	
Braille_Text_Show:
	.braille "AND SHOW$"
	
Braille_Text_New::
	.braille "A NEW$"
	
Braille_Text_Generation::
	.braille "GENERATION$"
	
Braille_Text_Meaning::
	.braille "THE MEANING$"
	
Braille_Text_Adventure::
	.braille "OF ADVENTURE$"
	
Braille_Text_Discovery::
	.braille "DISCOVERY$"
	
Braille_Text_Joy::
	.braille "AND JOY.$"	
	
Braille_Text_Three::
	.braille "IN THREE$"
	
Braille_Text_Caverns::
	.braille "CAVERNS$"
	
Braille_Text_Sealed::
	.braille "WE SEALED$"
	
Braille_Text_Away::
	.braille "AWAY THE$"
	
Braille_Text_Pokemon::
	.braille "POKEMON.$"
	
Braille_Text_ForWe::
	.braille "FOR WE$"
	
Braille_Text_Feared::
	.braille "FEARED THEM.$"
	
Braille_Text_Two::
	.braille "OUR TWO$"
	
Braille_Text_Protectors::
	.braille "PROTECTORS$"
	
Braille_Text_Watch::
	.braille "WATCH OVER$"
	
Braille_Text_Them::
	.braille "THEM$"
	
Braille_Text_Peace::
	.braille "IN PEACE.$"
	
Braille_Text_You::
	.braille "YOU WHO$"
	
Braille_Text_Disrupted::
	.braille "DISRUPTED$"
	
Braille_Text_ThePeace::
	.braille "THE PEACE$"
	
Braille_Text_Bested::
	.braille "AND BESTED$"
	
Braille_Text_OneOf::
	.braille "ONE OF THE$"
	
Braille_Text_Guardians::
	.braille "GUARDIANS.$"
	
Braille_Text_Door::
	.braille "A DOOR$"
	
Braille_Text_Opens::
	.braille "OPENS$"
	
Braille_Text_Eternal::
	.braille "AN ETERNAL$"
	
Braille_Text_Pokemon2::
	.braille "POKEMON$"
	
Braille_Text_Waits::
	.braille "WAITS.$"
