MonitoringStation_Office_Text_BlockAdmin::
	.string "The exit is blocked by a strange\n"
	.string "force.$"
	
MonitoringStation_Office_Text_Admin::
	.string "Wait!!$"
	
MonitoringStation_Office_Text_AdminHelp::
	.string "I will help you.\p"
	.string "I can't just keep helping only\n"
	.string "myself.$"
	
MonitoringStation_Office_Text_AdminNo::
	.string "No!\n"
	.string "You stupid kid!\p"
	.string "It's a GHOST-type POKéMON!$"
	
MonitoringStation_Office_Text_AdminPokemon::
	.string "Go, DUSCLOPS!$"
	
MonitoringStation_Office_Text_AdminAttack::
	.string "Use SHADOW PUNCH!!$"
	
MonitoringStation_Office_Text_AdminComeBack::
	.string "DUSCLOPS! Come back!$"
	
MonitoringStation_Office_Text_AdminKey::
	.string "… Go pick up that RED KEY.\p"
	.string "It's right there, on the desk.$"
	
MonitoringStation_Office_Text_Talk::
	.string "Yeah, I'm sorry for causing all\n"
	.string "this trouble.\p"
	.string "I hope I managed to right my wrongs\n"
	.string "by helping you out.\p"
	.string "While being ambushed by the monster,\n"
	.string "I realized it looked a lot like\p"
	.string "a KABUTOPS.\p"
	.string "Going by the information I heard from\n"
	.string "the GRUNT who accompanied me,\p"
	.string "I concluded that the monster is\n"
	.string "some sort of GHOST-type variant.\p"
	.string "It seems to be gone now, but maybe\n"
	.string "there is more to this…$"
	
MonitoringStation_Office_Text_NotDone::
	.string "You really shouldn't be playing\n"
	.string "around at a time like this.\p"
	.string "Go pick up that RED KEY.$"
	
MonitoringStation_Office_Text_Done::
	.string "Okay, let's go.$"
	
MonitoringStation_Office_Text_Text::
	.string "PETREL's log:\n"
	.string "Number 32\p"
    .string "GIOVANNI's whereabouts are still\n"
	.string "a complete mystery.\p"
	.string "Some rumors say he's gone to the\n"
	.string "JOHTO region to establish a new\p"
	.string "base of operations there.\p"
	.string "Other rumors say he's searching for\n"
	.string "powerful POKéMON, possibly on\p"
	.string "the SEVII ISLANDS.\p"
	.string "Personally, I think he's simply\n"
	.string "biding his time.\p"
	.string "Testing our loyalty, waiting for\n"
	.string "us to find him instead.\p"
	.string "But before that happens, we should\n"
	.string "build a stronger, more resilient\p"
	.string "TEAM ROCKET.\p"
	.string "Only then will we be worthy of\n"
	.string "our BOSS's attention.\p"
	.string "Otherwise, he may just form a new\n"
	.string "organization…$"