FakePallet2_Text_Mom::
	.string "You're finally awake!\n"
	.string "I was so worried!$"
	
FakePallet2_Text_Mom2::
	.string "You were brought back home while\n"
	.string "you were fast asleep.\p"
	.string "I have no idea what happened, but\n"
	.string "I'm glad to see you are okay.$"
	
FakePallet2_Text_Mom3::
	.string "You know…\p"
	.string "It's been hard here at home without\n"
	.string "you around.\p"
	.string "I don't like to ask this, but could\n"
	.string "you stay a bit longer this time?\p"
	.string "I've been so worried all this time…\n"
	.string "You know what happened to DAD.\p"
	.string "Maybe you could bring your POKéMON\n"
	.string "to PROFESSOR OAK, so he can take\p"
	.string "care of them, while you live\n"
	.string "with me.\p"
	.string "I don't want to force you… but…\n"
	.string "It really is for the best…\p"
	.string "YOU DO NOT HAVE A CHOICE!$"
	
