NewMap2_MapScripts::
	.byte 0

Brock2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_BROCK_REMATCH_CHALLENGE, Gym_Text_Done
	end

Misty2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_MISTY_REMATCH_CHALLENGE, Gym_Text_Done
	end

Surge2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_LT_SURGE_REMATCH_CHALLENGE, Gym_Text_Done
	end

Erika2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_ERIKA_REMATCH_CHALLENGE, Gym_Text_Done
	end

Koga2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_KOGA_REMATCH_CHALLENGE, Gym_Text_Done
	end

Sabrina2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_SABRINA_REMATCH_CHALLENGE, Gym_Text_Done
	end

Blaine2::
	trainerbattle_single_no_intro_text TRAINER_LEADER_BLAINE_REMATCH_CHALLENGE, Gym_Text_Done
	end