MonitoringStation_Quarters_Text_Funny::
	.string "Still here?!\p"
	.string "Wait…\n"
	.string "Everyone else left the base?!\p"
	.string "Ahh, finally I will have some peace\n"
	.string "and quiet around here!$"

MonitoringStation_Quarters_Text_RocketM1::
	.string "Can't you stop bothering me?\n"
	.string "I'm watching TV!$"
	
MonitoringStation_Quarters_Text_RocketM2::
	.string "Stress always makes me hungry.\p"
	.string "I hope they still got something\n"
	.string "good in here…$"
	
MonitoringStation_Quarters_Text_RocketM3::
	.string "You're looking for a YELLOW KEY?\p"
	.string "The UNDERBOSS is still hiding away,\n"
	.string "so you should go find our ADMIN.\p"
	.string "You must have ran into our her\n"
	.string "somewhere along the way.\p"
	.string "The ADMIN is supposed to have a\n"
	.string "YELLOW KEY on her.\p"
	.string "…… …… …… ……\p"
	.string "If she didn't mention it whatsoever,\n"
	.string "she must be hiding something…\p"
	.string "Maybe we should go talk to her.\p"
	.string "I want to get to the bottom of this\n"
	.string "strange behavior.\p"
	.string "I will lead the way.$"
	
MonitoringStation_Quarters_Text_RocketM4::
	.string "Why did you open the door?!\p"
	.string "Now, that monster can get in here\n"
	.string "anytime it wants to!$"
	
MonitoringStation_Quarters_Text_RocketF1::
	.string "Shhht!\p"
	.string "Can't you see that I'm hiding,\n"
	.string "you little twerp?$"
	
MonitoringStation_Quarters_Text_RocketF2::
	.string "Some people claim that our ADMIN\n"
	.string "has been plotting to take over\p"
	.string "the position of SEVII's UNDERBOSS.$"
	