MonitoringStation_ConferenceRoom_Text_RocketM1::
	.string "Yeah, we were notified that you had\n"
	.string "somehow snuck your way in.\p"
	.string "The pipsqueak you saw near the lift\n"
	.string "is right there, trying to reach his\p"
	.string "family.\p"
	.string "He rushed in here the moment the\n"
	.string "emergency doors reopened.\p"
	.string "Hahaha, poor guy.$"

MonitoringStation_ConferenceRoom_Text_RocketM2::
	.string "Right now, I don't feel like talking\n"
	.string "to some stuck-up kid.\p"
	.string "Go find someone else to bother!$"

MonitoringStation_ConferenceRoom_Text_RocketM3::
	.string "You're trying to find a way to escape\n"
	.string "this place?\p"
	.string "Hm. You might want to look for a way\n"
	.string "to get inside the personal office\p"
	.string "of our UNDERBOSS.\p"
	.string "You will need a YELLOW KEY\n"
	.string "for that.\p"
	.string "I don't have a YELLOW KEY,\n"
	.string "but I got a BLUE KEY.\p"
	.string "It will help you access more rooms\n"
	.string "within this complex.$"
	
MonitoringStation_ConferenceRoom_Text_ObtainedBlueKey::
	.string "{PLAYER} received a BLUE KEY\n"
	.string "from the TEAM ROCKET GRUNT!$"

MonitoringStation_ConferenceRoom_Text_RocketM32::
	.string "I hope you manage to reach the\n"
	.string "UNDERBOSS without running into\p"
	.string "trouble.$"

MonitoringStation_ConferenceRoom_Text_RocketF1::
	.string "If that monster dares to set\n"
	.string "a foot inside this room,\p"
	.string "it will have to contend with my\n"
	.string "powerful POKéMON…$"

MonitoringStation_ConferenceRoom_Text_RocketF2::
	.string "I'm s-so n-n-nervous!\p"
	.string "Are we even going to survive\n"
	.string "i-in here…?$"

MonitoringStation_ConferenceRoom_Text_Scientist1::
	.string "SIGH…\p"
	.string "I warned them, you know.\p"
	.string "They should have left that EMERALD\n"
	.string "inside that cave.\p"
	.string "They should never have opened that\n"
	.string "cavern in the first place.\p"
	.string "That EMERALD turned out to be\n"
	.string "completely useless anyway.$"

MonitoringStation_ConferenceRoom_Text_Scientist2::
	.string "I'm looking for a way to subdue\n"
	.string "that thing.\p"
	.string "But so far, I've found nothing of\n"
	.string "any use…$"

MonitoringStation_ConferenceRoom_Text_Text::
	.string "Entry: Sept. 16\n"
    .string "The Dig\p"
	.string "Shortly after this base was built,\n"
	.string "large energy readings were picked\p"
	.string "up by our radar technology.\p"
	.string "The readings came from even further\n"
	.string "below ground.\p"
	.string "We ended up digging our way into a\n"
	.string "small cavern, where we found a\p"
	.string "large green gemstone:\n"
	.string "the EMERALD.\p"
	.string "It was clear the readings came\n"
	.string "from this particular stone.\p"
	.string "Despite some skepticism among the\n"
	.string "research team, our UNDERBOSS\p"
	.string "ordered the stone to be taken and\n"
	.string "subjected to rigorous testing.\p"
	.string "Unfortunately, initial tests failed\n"
	.string "to unlock the powers hidden within\p"
	.string "the EMERALD…$"

MonitoringStation_ConferenceRoom_Text_RocketM4::
	.string "Please, just answer the darn phone!\n"
	.string "Why is it always me?!$"