MonitoringStation_Pokemon_Text_Scared::
	.string "The POKéMON inside is trembling\n"
	.string "with fear.$"
	
MonitoringStation_Pokemon_Text_Text::
	.string "Amount of POKéMON currently\n"
	.string "confiscated: 16.$"
	
MonitoringStation_Pokemon_Text_Text2::
	.string "DO NOT BE AFRAID.\n"
	.string "ENTER THE CAGE.$"
	
MonitoringStation_Pokemon_Text_PutYourselfInCage::
	.string "Step inside the cage?$"
	
MonitoringStation_Pokemon_Text_StepInCage::
	.string "{PLAYER} stepped inside the cage.$"