FiveIsland_ResortGorgeous_House_Text_SelphyWhatsThis::
    .string "Oh, and what do you want?\p"
    .string "A letter from PROFESSOR OAK,\n"
	.string "you say?\p"
	.string "And you've been asked to deliver\n"
	.string "this to me, of all people?\p"
	.string "What's this world coming to…\p"
	.string "Besides, I don't even know\n"
	.string "a PROFESSOR OAK!\p"
	.string "Oh well, just stop staring and\n"
	.string "hand me that letter!$"

FiveIsland_ResortGorgeous_House_Text_DeliveredLetter::
    .string "{PLAYER} delivered OAK'S LETTER.$"

FiveIsland_ResortGorgeous_House_Text_SelphyThisLetter::
    .string "This is impossible…\n"
	.string "How can this be?\p"
	.string "Listen well, my friend.\p"
	.string "Since I have nobody else to talk to,\n"
	.string "I'd like to disclose the contents of\p"
	.string "this letter to you.\p"
	.string "It seems this OAK person was once\n"
	.string "very close to my mother.\p"
	.string "I think you've met her a few times,\n"
	.string "when challenging the ELITE FOUR.\p"
	.string "After all, my mother is none other\n"
	.string "than AGATHA of the ELITE FOUR!\p"
	.string "I guess I should be proud of her,\n"
	.string "but I never liked my mother much.\p"
	.string "The only thing she cares about is\n"
	.string "POKéMON battles!\p"
	.string "She left me and my father behind to\n"
	.string "focus on those stupid fights.\p"
	.string "In his letter, OAK writes he is sorry\n"
	.string "for my mother's bitter behavior.\p"
	.string "He also explains why he feels\n"
	.string "responsible for all this.\p"
	.string "But surely he didn't ask you to head\n"
	.string "all the way here, just to deliver\p"
	.string "this letter to me?\p"
	.string "He does mention an incident that\n"
	.string "took place within the LOST CAVE,\p"
	.string "where you found and saved me.\p"
	.string "Maybe you should go take a look,\n"
	.string "you may find something in there.\p"
	.string "I wish you the best of luck with\n"
	.string "your search.$"
	
	
	
FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish:: @ 81A42A0
    .string "SELPHY: Oh?\n"
    .string "What do you want?\p"
    .string "Oh, but that doesn't matter.\p"
    .string "I am exquisitely bored.\n"
    .string "Please, hear my wish.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease:: @ 81A4315
    .string "I wish to see a POKéMON.\n"
    .string "A darling {STR_VAR_1}.\p"
    .string "I want to see one right away.\n"
    .string "Please, make my wish come true.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting:: @ 81A437A
    .string "SELPHY: Oh, I'm tired of this.\n"
    .string "I'm tired of waiting for you.\p"
    .string "I'll forgive you this time, but\n"
    .string "please don't fail me next time.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou:: @ 81A43F7
    .string "SELPHY: Oh, hello, there.\p"
    .string "Oh, my gracious. That must be the\n"
    .string "{STR_VAR_1} you caught for me.\p"
    .string "Giggle…\n"
    .string "I see a resemblance to you.\p"
    .string "Thank you so kindly.\p"
    .string "… …  … …  … …\n"
    .string "Is something the matter?\p"
    .string "You may leave.\p"
    .string "… …  … …  … …\n"
    .string "Oh, fine. I understand now.\p"
    .string "SEBASTIAN!\n"
    .string "I need you here this instant!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady:: @ 81A450B
    .string "Butler: Yes, my lady.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation:: @ 81A4521
    .string "SELPHY: See to it that this person\n"
    .string "is given a token of appreciation.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid:: @ 81A4566
    .string "Butler: I shall do as you bid,\n"
    .string "my lady.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks:: @ 81A458E
    .string "Butler: I sincerely thank you for\n"
    .string "pleasing Lady SELPHY.\p"
    .string "Please accept this as her thanks…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull:: @ 81A45E8
    .string "Butler: Your BAG appears to be\n"
    .string "unfortunately full.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing:: @ 81A461B
    .string "Oh…\n"
    .string "How disappointing.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck:: @ 81A4632
    .string "SELPHY: I wish you the best of\n"
    .string "luck.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun:: @ 81A4657
    .string "Butler: The smile of Lady SELPHY\n"
    .string "has the brilliance of the sun.\p"
    .string "Please, I beg you to bring joy\n"
    .string "to Lady SELPHY.$"

