GymLeaderRematchTemp_MapScripts::
	.byte 0

GymLeaderRematchTemp_EventScript_CitySign::
	msgbox GymLeaderRematchTemp_Text_Sign, MSGBOX_SIGN
	end

GymLeaderRematchTemp_Text_Sign::
	.string "Welcome to this interior,\n"
	.string "designed to battle KANTO's\l"
	.string "GYM LEADERS for now.\p"
	.string "Until DEOKISHISU updates the base\n"
	.string "used for this hack, this is how\l"
	.string "you will have to rematch LEADERS.\p"
	.string "This house features three rooms.\p"
	.string "Each room contains a team for every\n"
	.string "GYM LEADER save for GIOVANNI.\p"
	.string "This room contains the weakest\n"
	.string "version of each LEADER.\p"
	.string "The next contains stronger teams.\n"
	.string "The last one contains the strongest.\p"
	.string "This is a TEMPORARY room, and will\n"
	.string "be properly replaced by a GYM house\l"
	.string "according to quality standards.$"