BattleTower_BattleRoom_Text_19ACDC::
	.string "We will restore your POKéMON to\n"
	.string "full health.$"

BattleTower_BattleRoom_Text_19AD09::
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleTower_BattleRoom_Text_19AD3C::
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleTower_BattleRoom_Text_19AD66::
	.string "Would you like to cancel your\n"
	.string "BATTLE ROOM challenge?$"

BattleTower_BattleRoom_Text_1C6CE1::
	.string "SAVING...\n"
	.string "DON'T TURN OFF THE POWER.$"

BattleTower_BattleRoom_Text_1C6D05::
	.string "{PLAYER} saved the game.$"

BattleTower_BattleRoom_BrainAnabel_Intro::
	.string "Greetings…\p"
	.string "I am the TOWER TYCOON, and I am in\n"
	.string "charge of running the BATTLE TOWER…\p"
	.string "The reason I've come to see you…\n"
	.string "Well, there is but one reason…\p"
	.string "Let me see your talent in\n"
	.string "its entirety…$"
