BattleTower_BattleRoom_Text_Heal::
	.string "We will restore your POKéMON to\n"
	.string "full health.$"

BattleTower_BattleRoom_Text_OpponentAnnounce::
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleTower_BattleRoom_Text_ConfirmSaveAndQuit::
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleTower_BattleRoom_Text_19AD66::
	.string "Would you like to cancel your\n"
	.string "BATTLE ROOM challenge?$"

BattleTower_BattleRoom_Text_BrainAnnounce::
	.string "Excuse me, but…\p"
	.string "Our leader, the TOWER TYCOON, is on\n"
	.string "her way here, eager to battle you.\p"
	.string "She should be arriving\n"
	.string "very shortly.\p"
	.string "You will be facing the TOWER TYCOON.\n"
	.string "Are you prepared?$"

BattleTower_BattleRoom_Text_BrainAnnounce_Repeat::
	.string "You will be facing the TOWER TYCOON.\n"
	.string "Are you prepared?$"

BattleTower_BattleRoom_Text_System_Saving::
	.string "SAVING...\n"
	.string "DON'T TURN OFF THE POWER.$"

BattleTower_BattleRoom_Text_1C6D05::
	.string "{PLAYER} saved the game.$"

BattleTower_BattleRoom_BrainAnabel_Intro::
	.string "Greetings…\p"
	.string "I am the TOWER TYCOON, and I am in\n"
	.string "charge of running the BATTLE TOWER…\p"
	.string "The reason I've come to see you…\n"
	.string "Well, there is but one reason…\p"
	.string "Let me see your talent in\n"
	.string "its entirety…$"

BattleTower_BattleRoom_BrainAnabel_Defeated_InBattle::
	.string "Okay, I understand…$"

BattleTower_BattleRoom_BrainAnabel2_Intro::
	.string "ANABEL: You really did come back to\n"
	.string "see me…\p"
	.string "… … … … … …\p"
	.string "You've won straight matches to see me…\n"
	.string "I won't have to hold back against you…\p"
	.string "It's been too long now…\p"
	.string "Too long since I've been able to battle\n"
	.string "without thinking about anything…\p"
	.string "Let's begin, shall we?$"

BattleTower_BattleRoom_BrainAnabel2_Defeated_InBattle::
	.string "Thank you…$"
