MonitoringStation_Text_ExecutiveFinal::
	.string "You really are something, aren't you?\n"
	.string "CHAMPION of KANTO, and our savior.\p"
	.string "I know you won't join our ranks,\n"
	.string "and that means we will remain\p"
	.string "enemies.\p"
	.string "Please don't get in our way again,\n"
	.string "or we will have to take action.\p"
	.string "Goodbye!$"

MonitoringStation_Text_AdminFinal::
	.string "I thank you for helping us out\n"
	.string "of this predicament.\p"
	.string "You should consider joining\n"
	.string "TEAM ROCKET.\p"
	.string "Hm? You've heard that before?\p"
	.string "Well, that ought to motivate you\n"
	.string "even further!$"
	
MonitoringStation_Text_StorageFinal::
	.string "I guess that's it for our time\n"
	.string "inside this awesome base.\p"
	.string "After all this commotion, the police\n"
	.string "will come looking for us.\p"
	.string "Our cover will be totally blown, and\n"
	.string "TRAINER TOWER will have to quit.\p"
	.string "Despite our pretty not-nice plans to\n"
	.string "capture POKéMON from our visitors,\p"
	.string "many TRAINERS have been enjoying\n"
	.string "this facility.\p"
	.string "So the UNDERBOSS decided to leave\n"
	.string "it to the employees upstairs.\p"
	.string "Oh, and yeah…\p"
	.string "… Thanks for your help.$"

MonitoringStation_Text_Admin::
	.string "…… … that door coming along?\n"
	.string "We haven't got all day!$"
	
MonitoringStation_Text_StorageGrunt::
	.string "This stuff takes time!\p"
	.string "Without the key, I need to override\n"
	.string "the lock manually.\p"
	.string "You could have just helped that kid\n"
	.string "get to the UNDERBOSS by giving him\p"
	.string "that YELLOW KEY…$"
	
MonitoringStation_Text_Quartet::
	.string "Hold it!\n"
	.string "You guys got some explaining to do.$"
	
MonitoringStation_Text_Admin2::
	.string "And who are you to order\n"
	.string "me around?\p"
	.string "I will report your misbehavior to\n"
	.string "the UNDERBOSS.\p"
	.string "You can explain it to…$"
	
MonitoringStation_Text_Executive::
	.string "I AM the UNDERBOSS, you nitwit!\p"
	.string "I've been undercover as a GRUNT for\n"
	.string "a while now, in order to uncover\p"
	.string "your scheme to overthrow me.$"
	
MonitoringStation_Text_StorageGrunt2::
	.string "Uh-oh…$"
	
MonitoringStation_Text_Executive2::
	.string "And now, you can explain to me why\n"
	.string "you wanted to leave me, and so\p"
	.string "many GRUNTS, behind.$"
	
MonitoringStation_Text_Admin3::
	.string "Alright then. I wanted to be the\n"
	.string "UNDERBOSS. So what?$"
	
MonitoringStation_Text_Executive3::
	.string "It's not just that…\p"
	.string "You were willing to leave everyone\n"
	.string "behind just to accomplish that.\p"
	.string "You wanted to sacrifice all your\n"
	.string "colleagues to a monster to get\p"
	.string "what you want.\p"
	.string "You aren't worthy of the rank of\n"
	.string "ADMIN, let alone the rank of\p"
	.string "UNDERBOSS.$"
	
MonitoringStation_Text_TookYellowKey::
	.string "The UNDERBOSS took the YELLOW KEY\n"
	.string "from the ADMIN.$"
	
MonitoringStation_Text_Executive4::
	.string "I think you need this more than\n"
	.string "she ever will…$"
	
MonitoringStation_Text_ObtainedYellowKey::
	.string "{PLAYER} received a YELLOW KEY\n"
	.string "from the UNDERBOSS!$"
	
MonitoringStation_Text_Executive5::
	.string "The ADMIN had this key all along.\n"
	.string "She just wanted to get away\p"
	.string "while leaving me behind in my\n"
	.string "office, cowering in fear.\p"
	.string "Unfortunately for her, I wasn't\n"
	.string "in my office.\p"
	.string "Anyway, my RED KEY lies on my desk\n"
	.string "in my personal office.\p"
	.string "You can use it to open this door\n"
	.string "in a second, rather than taking\p"
	.string "hours like these buffoons.$"
	
MonitoringStation_Text_StorageGruntLoose::
	.string "I got nothing to do with it!\n"
	.string "I swear!$"
	
MonitoringStation_Text_AdminLoose::
	.string "I might have gone too far\n"
	.string "with this…$"
	
MonitoringStation_Text_ExecutiveIntro::
	.string "Aah, this is much better!\p"
	.string "That GRUNT outfit is so very\n"
	.string "uncomfortable.$"
	
MonitoringStation_Text_ExecutiveKey::
	.string "Did you manage to get your hands on\n"
	.string "the RED KEY?$"
	
MonitoringStation_Text_ExecutiveYay::
	.string "You did a very good job.\n"
	.string "For a kid, that is…\p"
	.string "I leave the honor of opening\n"
	.string "the door to you.$"
	
MonitoringStation_Text_ExecutiveAww::
	.string "Please go get that key quickly.\n"
	.string "All of our lives depend on it.$"

MonitoringStation_Text_RedDoorGone::
	.string "The RED KEY unlocked the door!$"

MonitoringStation_Text_RedDoor::
	.string "This door is electronically locked.\n"
	.string "A specific keycard can unlock it.$"

MonitoringStation_Text_OutOfOrder::
	.string "The elevator seems to be out\n"
	.string "of order.$"

MonitoringStation_Text_RocketWhat::
	.string "What in tarnation are you doing\n"
    .string "here?!\p"
    .string "This place is off-limits to anyone\n"
    .string "but members of TEAM ROCKET!\p"
	.string "It's time to teach you a lesson!$"
	
MonitoringStation_Text_RocketAh::
	.string "What was that noise about?!$"
	
MonitoringStation_Text_RocketCheck::
	.string "I have to investigate.\p"
	.string "A POKéMON may have broken out of\n"
	.string "the containment area!\p"
	.string "You just stay put. I will be back\n"
	.string "in a jiffy.\p"
	.string "NO wandering around this base,\n"
	.string "understood?$"
	
MonitoringStation_Text_RocketNo::
	.string "AAAAAAAGHHHHHH!!!!$"