Prototype_SeviiIsle_6_MapScripts::
	.byte 0

Prototype_SeviiIsle_6_EventScript_RouteSign::
	msgbox Prototype_SeviiIsle_6_Text_RouteSign, MSGBOX_SIGN
	end

Prototype_SeviiIsle_6_Text_RouteSign::
    .string "AURUM PATH \p"
    .string "Warning!\n"
    .string "Impassable sea currents ahead!$"

Aurum_Road_EventScript_Youngster::
	msgbox Aurum_Road_Text_Umbilical_Tower, MSGBOX_NPC
	end

Aurum_Road_Text_Umbilical_Tower::
	.string "The old man in that tower\n"
	.string "is so weird!\p"
	.string "He just keeps laughing at me,\n"
	.string "saying I am not worthy.\p"
	.string "I'll show the old coot!\n"
	.string "Wait until he sees my POKéMON!$"