Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If you have obtained the MARSHBADGE\n"
    .string "from SAFFRON CITY, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "PROF. OAK entrusted me with the\n"
    .string "{STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me check your\n"
    .string "TRAINED CARD right now…$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Great! You have defeated SABRINA\n"
    .string "and obtained her GYM BADGE!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "EXP. SHARE is an item to be held\n"
    .string "by a POKéMON.\p"
    .string "The POKéMON will receive a share\n"
    .string "of the EXP. Points without having\l"
    .string "to battle.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A large, shining bird is flying\n"
    .string "toward the sea.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It looks like a small island on\n"
    .string "the horizon!$"

