CinnabarIsland_BerryFarm_Text_Farm::
	.string "Hello there!\p"
	.string "I'm terribly sorry, but our BERRIES\n"
	.string "are specifically grown for folks\p"
	.string "who live on CINNABAR ISLAND.\p"
	.string "However, I could tell you about the\n"
	.string "history of our farm if you like.\p"
	.string "Do you want to hear it?$"
	
CinnabarIsland_BerryFarm_Text_Okay::
	.string "Aw…\n"
	.string "I love telling people our story.\p"
	.string "Oh well. Come again!$"
	
CinnabarIsland_BerryFarm_Text_FarmExplain::
	.string "This farm was built by our ancestors,\n"
	.string "the first settlers of what we now\p"
	.string "call CINNABAR ISLAND.\p"
	.string "The rich, volcanic soil gave them the\n"
	.string "perfect opportunity to plant our\p"
	.string "BERRY TREES.\p"
	.string "Our BERRIES quickly became famous,\n"
	.string "and soon, people started flocking\p"
	.string "to this island just to get a taste\n"
	.string "of what we had to offer.\p"
	.string "Eventually, folks began to settle,\n"
	.string "and this farm became the source\p"
	.string "of food for every islander.\p"
	.string "To this day, the farm remains\n"
	.string "a family business.\p"
	.string "Although we don't sell BERRIES to\n"
	.string "outsiders, I want to show you my\p"
	.string "appreciation for your interest\n"
	.string "in this farm and its history.\p"
	.string "Here, take this.$"
	
CinnabarIsland_BerryFarm_Text_ObtainedLumBerry::
    .string "{PLAYER} received a LUM BERRY\n"
	.string "from the owner of the farm!$"
	
CinnabarIsland_BerryFarm_Text_Thanks::
    .string "I hope you enjoy your stay\n"
	.string "on CINNABAR ISLAND.$"
	
CinnabarIsland_BerryFarm_Text_Hello::
	.string "Hello, and welcome to the\n"
	.string "CINNABAR BERRY FARM.$"
	
CinnabarIsland_BerryFarm_Text_Farmer::
	.string "Hey there!\p"
	.string "I work the land, growing our trees\n"
	.string "and picking berries once they've\p"
	.string "ripened enough.$"

CinnabarIsland_BerryFarm_Text_GiveJar::
	.string "Hey there!\p"
	.string "I work the land, growing our trees\n"
	.string "and picking berries once they've\p"
	.string "ripened enough.$"
	.string "To give people a taste of what you\n"
	.string "can do with BERRIES, we are giving\p"
	.string "away jars filled with BERRY POWDER\n"
	.string "for free.\p"
	.string "You can have one too!$"
	
CinnabarIsland_BerryFarm_Text_ObtainedBerryPowder::
    .string "{PLAYER} received the BERRY POWDER\n"
	.string "from the farm owner's son!$"
	
CinnabarIsland_BerryFarm_Text_Enjoy::
	.string "You can do a lot of things\n"
	.string "with BERRIES.\p"
	.string "For example, you can crush them\n"
	.string "into BERRY POWDER.\p"
	.string "You can then use BERRY POWDER to\n"
	.string "concote all sorts of medicine.\p"
	.string "Bet you didn't know that, huh?$"
	
CinnabarIsland_BerryFarm_Text_Woman::
	.string "I wonder what BERRIES we should\n"
	.string "eat for breakfast tomorrow.$"