TohjoFallsSecret_MapScripts::
	.byte 0

TohjoFalls_EventScript_Radio::
	msgbox TohjoFalls_Text_Radio, MSGBOX_NPC
	end

TohjoFalls_Text_Radio::
    .string "It's an old radio.\p"
    .string "It seems to have been used\n"
    .string "very recently.$"

TohjoFalls_EventScript_Notes::
	msgbox TohjoFalls_Text_Notes, MSGBOX_SIGN
	end

TohjoFalls_Text_Notes::
    .string "Along with the retrieval of MEWTWO,\n"
    .string "I have been aiming to find and\p"
    .string "capture the mythical POKéMON\n"
    .string "known as DEOXYS.\p"
    .string "DEOXYS was only recently discovered,\n"
    .string "when a meteorite landed somewhere\p"
    .string "in the HOENN region.\p"
    .string "This meteorite contained the DNA\n"
    .string "of this creature.\p"
    .string "No one has actually seen DEOXYS before,\n"
    .string "although some locals from a recently\p"
    .string "abandoned island claimed an alien\n"
    .string "devastated their civilization.\p"
    .string "After this ninth SEVII ISLAND was\n"
    .string "left to the seas, travel to it\p"
    .string "was made impossible.\p"
    .string "Only people with an AURORA TICKET\n"
    .string "were taken to this place.\p"
    .string "Such tickets have been destroyed,\n"
    .string "and production was discontinued.\p"
    .string "However, I have found the last\n"
    .string "remaining ticket.\p"
    .string "I have visited BIRTH ISLAND,\n"
    .string "and I can safely say:\p"
    .string "DEOXYS is there.\p"
    .string "Right now, I have to prepare myself\n"
    .string "and my POKéMON to catch it.\p"
    .string "DEOXYS will soon be mine, and no one\n"
    .string "will be able to stop me!$"
