MtMoon_Square_Text_LatiasFled::
    .string "The LATIAS flew away\n"
    .string "in the blink of an eye.$"

MtMoon_Square_Text_Sign::
    .string "This is MT. MOON SQUARE.\p"
	.string "Please don't litter. Put trash\n"
	.string "where it belongs!$"

MtMoon_Square_Text_MudkipNoise::
    .string "Mrrfrk!!$"

MtMoon_Square_Text_MudkipAngryFood::
    .string "You stepped on a SITRUS BERRY!\p"
	.string "The MUDKIP looks very upset.\p"
	.string "It probably will stay angry unless\n"
	.string "you give it another SITRUS BERRY.\p"
	.string "Give MUDKIP a SITRUS BERRY?$"
	
MtMoon_Square_Text_MudkipStillAngry::
	.string "MUDKIP remains upset with you.$"

MtMoon_Square_Text_MudkipHappyJoin::
    .string "MUDKIP is no longer angry!\p"
	.string "It seems to really appreciate your\n"
	.string "kind gesture and wants to join you\p"
	.string "on your adventure.\p"
	.string "Do you want to bring MUDKIP along?$"
	
MtMoon_Square_Text_MudkipSad::
	.string "MUDKIP seems a little down.$"

MtMoon_Square_Text_ObtainedMudkip::
    .string "{PLAYER} obtained a MUDKIP!$"

MtMoon_Square_Text_Latias::
	.string "Huaaaaann!$"
	
MtMoon_Square_Text_AnabelCongrats::
	.string "You battled LATIAS.\n"
	.string "Well done…\p" 
	.string "It seems that LATIAS was hurt by\n"
	.string "another POKéMON.\p"
	.string "The CLEFAIRY came to her rescue…$"
	
MtMoon_Square_Text_AnabelAero::
	.string "The offending POKéMON seems to have\n"
	.string "flown away.\p"
	.string "Such an aggressive POKéMON…\n"
	.string "I wonder where it is now.\p"
	.string "It may be roaming throughout\n"
	.string "this region.\p"
	.string "…… …… ……\n"
	.string "Anyway.\p"
	.string "It seems I should not be touching\n"
	.string "LATIAS' forehead twice.\p"
	.string "Could it be…\p"
	.string "Could it be that LATIAS lets people\n"
	.string "touch it to give them a reason to\p"
	.string "travel the lands?\p"
	.string "Does LATIAS want to inspire people\n"
	.string "to see all the world has to offer?\p"
	.string "This quest has given me the chance\n"
	.string "to see all kinds of locations…\p"
	.string "In the end, it was all about\n"
	.string "the journey…\p"
	.string "Forgive me. I have a many things\n"
	.string "to think about…\p"
	.string "I hope we will meet again.$"