NewMap3_MapScripts::
	.byte 0

Brock3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_BROCK_CHALLENGE, Gym_Text_Done
	end

Misty3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_MISTY_CHALLENGE, Gym_Text_Done
	end

Surge3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_LT_SURGE_CHALLENGE, Gym_Text_Done
	end

Erika3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_ERIKA_CHALLENGE, Gym_Text_Done
	end

Koga3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_KOGA_CHALLENGE, Gym_Text_Done
	end

Sabrina3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_SABRINA_CHALLENGE, Gym_Text_Done
	end

Blaine3::
	trainerbattle_single_no_intro_text TRAINER_LEADER_BLAINE_CHALLENGE, Gym_Text_Done
	end