Route26WeekSisters_MapScripts::
	.byte 0

Route26WeekSisters_EventScript_Note::
	msgbox Route26WeekSisters_Text_Note, MSGBOX_SIGN
	end

Route26WeekSisters_Text_Note::
	.string "To my brothers and sisters:\p"
	.string "We take pride in serving\n"
	.string "POKéMON TRAINERS.\p"
	.string "When TRAINERS talk to you, give them\n"
	.string "something useful.\p"
	.string "Love,\n"
	.string "MONICA\p"
	.string "MONDAY, MONICA\n"
	.string "ROUTE 40\p"
	.string "TUESDAY, TUSCANY\n"
	.string "ROUTE 29\p"
	.string "WEDNESDAY, WESLEY\n"
	.string "LAKE OF RAGE\p"
	.string "THURSDAY, ARTHUR\n"
	.string "ROUTE 36\p"
	.string "FRIDAY, FRIEDA\n"
	.string "ROUTE 32\p"
	.string "SATURDAY, SANTOS\n"
	.string "BLACKTHORN CITY\p"
	.string "SUNDAY, SUNNY\n"
	.string "ROUTE 37$"