ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Whimper… Sniff…\n"
    .string "Oh! Please, help!\p"
    .string "A scary POKéMON appeared there\n"
    .string "a little while ago.\p"
    .string "It kept scaring.\n"
    .string "It made LOSTELLE scared.\p"
    .string "I'm too scared to move!\n"
    .string "But I want to go home…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Oh! Here it comes again!\n"
    .string "No! Go away! It's scaring me!\p"
    .string "Waaaaaaah!\n"
    .string "I want my daddy!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Ohh! That was so scary!\n"
    .string "Thank you!\p"
    .string "LOSTELLE came to pick some\n"
    .string "BERRIES.\p"
    .string "You can have this!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "What's your name?\p"
    .string "LOSTELLE's scared, so can I go\n"
    .string "with you to my daddy's house?\p"
    .string "Okay!\n"
    .string "Let's go home!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Your BERRY POUCH is full.\n"
    .string "I guess you don't want this.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Welcome to the BERRY FOREST\p"
    .string "Be friendly and share BERRIES with\n"
    .string "others and POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Beware of wild, BERRY-loving\n"
    .string "POKéMON!$"

ThreeIsland_BerryForest_Text_Flew::
    .string "The mysterious POKéMON disappeared\n"
    .string "in the blink of an eye!$"

ThreeIsland_BerryForest_Text_AnabelTalk::
    .string "That was the POKéMON\n"
	.string "named LATIAS…\p"
    .string "LATIAS flies so fast, you could not\n"
	.string "even see it take off…\p"
	.string "I am ANABEL, a TRAINER like you…\p"
	.string "Since you have managed to come here,\n"
	.string "we should test your potential…$"
	
ThreeIsland_BerryForest_Text_AnabelTalk2::
    .string "That was an interesting fight…\n"
    .string "You did do quite well…\p"
	.string "I will entrust you with my secret…\p"
	.string "Since I was born, I have been able\n"
	.string "to see into the minds of POKéMON\p"
	.string "that I have touched.\p"
	.string "As a child, LATIAS appeared to me,\n"
	.string "and let me touch its forehead.\p"
	.string "Ever since that day, I can see\n"
	.string "through the eyes of LATIAS.\p"
	.string "But I do not know what it intended\n"
	.string "when it let me touch its head…\p"
	.string "Ever since that day, I have been\n"
	.string "looking for a way to find it\p"
	.string "and to figure out the reason…\p"
	.string "Thanks to my gift, I can see where\n"
	.string "LATIAS resides as long as its eyes\p"
	.string "are open.\p"
	.string "However, I do not hail from\n"
	.string "these parts… … … …$"
	
ThreeIsland_BerryForest_Text_AnabelTalk3::
    .string "I want you to help me…\p"
    .string "You are the CHAMPION of KANTO.\p"
	.string "You likely know this region better\n"
	.string "than anyone else who lives in it.\p"
	.string "If I describe to you what I can see\n"
	.string "through the eyes of this LATIAS,\p"
	.string "you can tell me which location\n"
	.string "matches said description.\p"
	.string "Please let me concentrate…$"
	
ThreeIsland_BerryForest_Text_AnabelTalk4::
    .string "I saw… a small island…\n"
    .string "Not far from the one we are on.\p"
	.string "A busy marketplace…\n"
	.string "and a beach full of people…\p"
	.string "Yes, this is what I saw.\n"
	.string "Does this sound familiar to you?$"
	
ThreeIsland_BerryForest_Text_PlayerRelay::
	.string "{PLAYER} revealed the name of the\n"
	.string "perceived location to ANABEL.$"
	
ThreeIsland_BerryForest_Text_AnabelTalk5::
	.string "… … I see…\p"
	.string "Then I will go to that place.\n"
	.string "Feel free to meet me there…$"
	
ThreeIsland_BerryForest_Text_AnabelDefeat::
	.string "You are talented indeed…$"

ThreeIsland_BerryForest_Text_AnabelVictory::
	.string "You are strong…\n"
	.string "But not strong enough…$"
